pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -f demo/pom.xml clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f demo/pom.xml test'
            }
        }
    }
}
